//! OV2640 / OV5640 camera driver via ESP-IDF esp_camera component.
//!
//! Captures 320×240 QVGA in YUV422, converts to `Frame` (interleaved RGB +
//! luma plane), and publishes via `Arc<Mutex<Option<Frame>>>` — the same
//! pattern as `PiCamera` in the raspberry-pi crate.
//!
//! # GPIO pin assignments (Waveshare ESP32-S3-Touch-LCD-2)
//! These are the default FPC camera connector mapping. Verify against the
//! board schematic before use — Waveshare revisions sometimes differ.
//!
//!   SIOD (SDA)  GPIO 4   SCCB uses I2C1 (see CONFIG_SCCB_HARDWARE_I2C_PORT)
//!   SIOC (SCL)  GPIO 5   Touch uses I2C0 (GPIO48/47) — no conflict.
//!   XCLK        GPIO 15
//!   VSYNC       GPIO 6
//!   HREF        GPIO 7
//!   PCLK        GPIO 13
//!   D7 (Y9)     GPIO 16
//!   D6 (Y8)     GPIO 17
//!   D5 (Y7)     GPIO 18
//!   D4 (Y6)     GPIO 12
//!   D3 (Y5)     GPIO 10
//!   D2 (Y4)     GPIO 8
//!   D1 (Y3)     GPIO 9
//!   D0 (Y2)     GPIO 11
//!   PWDN / RESET not wired (-1)
//!
//! XCLK is generated by LEDC timer 1 + channel 1 (backlight uses timer 0 /
//! channel 0, so there is no conflict).

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::thread::{self, JoinHandle};
use std::time::Duration;

use esp_idf_hal::cpu::Core;
use esp_idf_hal::task::thread::ThreadSpawnConfiguration;

use faraday_core::camera::{Frame, ScanDiagnostics, ScanMode};

// ---------- board pin constants -------------------------------------------
//
// From the Waveshare ESP32-S3-Touch-LCD-2 CircuitPython board definition
// (ports/espressif/boards/waveshare_esp32_s3_touch_lcd_2/pins.c) — the same
// authoritative source the display/touch pins were taken from.
//
// Camera SCCB is on its own I2C bus (SDA=21, SCL=16), separate from the touch
// sensor (I2C0, GPIO48/47). No RESET line is wired; PWDN is GPIO17 (active
// high: esp_camera_init drives it HIGH then LOW to power the sensor on).

const CAM_PIN_PWDN: i32  = 17;
const CAM_PIN_RESET: i32 = -1;
const CAM_PIN_XCLK: i32  = 8;
const CAM_PIN_SIOD: i32  = 21; // TWI_SDA
const CAM_PIN_SIOC: i32  = 16; // TWI_CLK
const CAM_PIN_D7: i32    = 2;
const CAM_PIN_D6: i32    = 7;
const CAM_PIN_D5: i32    = 10;
const CAM_PIN_D4: i32    = 14;
const CAM_PIN_D3: i32    = 11;
const CAM_PIN_D2: i32    = 15;
const CAM_PIN_D1: i32    = 13;
const CAM_PIN_D0: i32    = 12;
const CAM_PIN_VSYNC: i32 = 6;
const CAM_PIN_HREF: i32  = 4;
const CAM_PIN_PCLK: i32  = 9;

// 20 MHz XCLK — standard for OV2640 and OV5640.
const CAM_XCLK_FREQ: i32 = 20_000_000;

// SVGA grayscale capture. The OV5640's VGA mode subsamples (aliased modules →
// quirc fits the grid but ECC always fails); its QVGA and SVGA modes bin pixels
// (clean, anti-aliased). SVGA decoded reliably in testing where VGA never did.
// We then box-average the crop ÷2 in software (see qr_decode) for speed, which
// also further cleans the modules. 480 KB/frame ran tear-free as grayscale.
const CAPTURE_W: u32 = 800;
const CAPTURE_H: u32 = 600;

// ---------- persistent QR-decode pipeline -----------------------------------
//
// The decoder thread needs a 96 KB stack (quircs puts large transient buffers
// on the stack). On the ESP32-S3, pthread/FreeRTOS stacks must live in internal
// SRAM, and a 96 KB *contiguous* block is right at the edge of what's available
// once the heap has been through one camera open/teardown cycle: the largest
// free internal block measured ~196 KB at boot, ~96 KB after the first cycle,
// then fragmented below 96 KB — so re-spawning the decoder on a later open()
// failed with ENOMEM ("spawn decoder: Not enough space").
//
// Fix: spawn the decoder exactly once (lazily, on the first camera open, when
// the heap is least fragmented) and keep it alive for the rest of the process.
// It only ever reads the shared `latest` luma buffer — it never touches the
// esp_camera hardware — so its lifetime is fully decoupled from camera
// init/deinit. When no camera is open we just gate it off via `decode_enabled`.
// The 16 KB reader stack is small enough to re-allocate reliably, so it stays
// tied to the camera-hardware lifetime (spawned in open, joined in drop).

struct QrPipeline {
    latest: Arc<Mutex<Option<Frame>>>,
    pending_qr: Arc<Mutex<Option<Vec<u8>>>>,
    diag: Arc<Mutex<ScanDiagnostics>>,
    small_qr_mode: Arc<AtomicBool>,
    decode_enabled: Arc<AtomicBool>,
    _decoder: JoinHandle<()>,
}

static PIPELINE: OnceLock<QrPipeline> = OnceLock::new();

/// The process-wide QR-decode pipeline. Spawns the decoder thread on first use.
fn pipeline() -> &'static QrPipeline {
    PIPELINE.get_or_init(QrPipeline::start)
}

impl QrPipeline {
    fn start() -> QrPipeline {
        let latest: Arc<Mutex<Option<Frame>>> = Arc::new(Mutex::new(None));
        let pending_qr: Arc<Mutex<Option<Vec<u8>>>> = Arc::new(Mutex::new(None));
        let diag: Arc<Mutex<ScanDiagnostics>> =
            Arc::new(Mutex::new(ScanDiagnostics::default()));
        let decode_enabled = Arc::new(AtomicBool::new(false));
        let small_qr_mode = Arc::new(AtomicBool::new(false));

        // Decoder thread — runs the quircs QR pipeline on the latest frame.
        // 96 KB stack: QR decoders can put large transient buffers on the stack
        // (a worst-case data matrix is tens of KB); 32 KB previously overflowed
        // into adjacent internal RAM and corrupted FreeRTOS task lists
        // (LoadProhibited in vListInsert). 96 KB leaves comfortable headroom.
        // Spawned once for the life of the process (see module note above), so
        // this allocation never has to compete with a fragmented heap.
        let latest_d = Arc::clone(&latest);
        let qr_d = Arc::clone(&pending_qr);
        let diag_d = Arc::clone(&diag);
        let mode_d = Arc::clone(&small_qr_mode);
        let decode_d = Arc::clone(&decode_enabled);

        // Pin the decoder to CPU1 (APP core). A single decode is CPU-bound for
        // ~1 s and runs at the default pthread priority (5), which is higher
        // than the main/GUI task (priority 1, pinned to CPU0). Without an
        // explicit affinity the scheduler can place it on CPU0, where it
        // preempts the GUI and freezes the camera preview for a full second per
        // attempt. CPU1 is the core the watchdog config already expects it on
        // (CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=n in sdkconfig.defaults).
        // Affinity comes only from the esp_pthread cfg (Thread::Builder can't
        // set it), so set it just for this spawn and restore the default after
        // so the reader (spawned later, on the main task) keeps default
        // placement; Builder::stack_size still sets the stack authoritatively.
        ThreadSpawnConfiguration {
            pin_to_core: Some(Core::Core1),
            ..Default::default()
        }
        .set()
        .expect("pin decoder thread to CPU1");
        let decoder = thread::Builder::new()
            .stack_size(96 * 1024)
            .spawn(move || decoder_loop(latest_d, qr_d, diag_d, mode_d, decode_d))
            .expect("spawn decoder (once, at first camera open)");
        ThreadSpawnConfiguration::default()
            .set()
            .expect("restore default thread spawn config");

        QrPipeline {
            latest,
            pending_qr,
            diag,
            small_qr_mode,
            decode_enabled,
            _decoder: decoder,
        }
    }
}

// ---------- public struct ---------------------------------------------------

pub struct EspCamera {
    fatal_err: Arc<Mutex<Option<String>>>,
    stop: Arc<AtomicBool>,
    _reader: Option<JoinHandle<()>>,
}

impl EspCamera {
    pub fn open() -> Result<Self, String> {
        // Ensure the persistent decoder exists (spawns once, on this first call).
        let pl = pipeline();

        // Start each scan session from a clean slate: drop any stale frame and
        // result from the previous session so the persistent decoder can't
        // surface an old QR before the new reader has published a fresh frame.
        // (The UR accumulator and diagnostics are reset by the decoder itself
        // when decode_enabled went false on the previous teardown.)
        if let Ok(mut g) = pl.latest.lock() {
            *g = None;
        }
        if let Ok(mut g) = pl.pending_qr.lock() {
            *g = None;
        }

        unsafe { init_camera()? };
        log::info!("esp_camera: init OK ({}x{} GRAYSCALE)", CAPTURE_W, CAPTURE_H);

        let fatal_err: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));
        let stop = Arc::new(AtomicBool::new(false));

        // Reader thread — grabs frames from the camera DMA, converts YUV422
        // to RGB+luma, publishes to `latest`. Stack: 16 KB for the conversion
        // buffers (320×240×5 bytes touched per frame). Re-spawned each open;
        // 16 KB allocates reliably even from a fragmented heap.
        let latest_w = Arc::clone(&pl.latest);
        let fatal_w = Arc::clone(&fatal_err);
        let stop_r = Arc::clone(&stop);
        let reader = thread::Builder::new()
            .stack_size(16 * 1024)
            .spawn(move || reader_loop(latest_w, fatal_w, stop_r))
            .map_err(|e| format!("spawn reader: {e}"))?;

        // No separate no-first-frame watchdog: the reader already declares the
        // camera dead (sets fatal_err, stops) after MAX_CONSECUTIVE_NULLS frame
        // timeouts, which covers the "camera never delivers" case.

        Ok(EspCamera {
            fatal_err,
            stop,
            _reader: Some(reader),
        })
    }

    pub fn latest(&self) -> Option<Frame> {
        pipeline().latest.lock().ok().and_then(|g| g.clone())
    }

    pub fn take_qr(&self) -> Option<Vec<u8>> {
        pipeline().pending_qr.lock().ok().and_then(|mut g| g.take())
    }

    pub fn set_decode_enabled(&self, on: bool) {
        pipeline().decode_enabled.store(on, Ordering::Relaxed);
    }

    pub fn set_small_qr_mode(&self, on: bool) {
        pipeline().small_qr_mode.store(on, Ordering::Relaxed);
    }

    pub fn take_fatal_err(&self) -> Option<String> {
        self.fatal_err.lock().ok().and_then(|mut g| g.take())
    }

    pub fn diagnostics(&self) -> ScanDiagnostics {
        pipeline().diag.lock().ok().map(|g| *g).unwrap_or_default()
    }
}

impl Drop for EspCamera {
    fn drop(&mut self) {
        // Stop decoding first so the persistent decoder parks (and resets its
        // UR accumulator + diagnostics) instead of chewing on the soon-to-be
        // stale frame while we tear the hardware down.
        pipeline().decode_enabled.store(false, Ordering::SeqCst);

        // Order matters: join the reader BEFORE deinit. The reader checks `stop`
        // only between frames and releases each frame buffer (esp_camera_fb_return)
        // before looping, so once it has exited no thread is touching camera
        // memory. Calling esp_camera_deinit() while the reader is still mid-frame
        // (copying fb.buf) would free the DMA buffers under it → use-after-free.
        //
        // esp_camera_fb_get() has an internal timeout, so the reader returns and
        // sees `stop` within ~1 s even without deinit.
        self.stop.store(true, Ordering::SeqCst);
        if let Some(h) = self._reader.take() {
            let _ = h.join();
        }
        unsafe {
            esp_idf_sys::camera::esp_camera_deinit();
        }
    }
}

// ---------- camera init (unsafe FFI) ----------------------------------------

unsafe fn init_camera() -> Result<(), String> {
    use esp_idf_sys::camera as cam;

    // Zero-initialise first so any fields not explicitly set below are at a
    // safe default (0 / false / null).
    let mut cfg: cam::camera_config_t = core::mem::zeroed();

    cfg.pin_pwdn  = CAM_PIN_PWDN;
    cfg.pin_reset = CAM_PIN_RESET;
    cfg.pin_xclk  = CAM_PIN_XCLK;
    cfg.pin_d7    = CAM_PIN_D7;
    cfg.pin_d6    = CAM_PIN_D6;
    cfg.pin_d5    = CAM_PIN_D5;
    cfg.pin_d4    = CAM_PIN_D4;
    cfg.pin_d3    = CAM_PIN_D3;
    cfg.pin_d2    = CAM_PIN_D2;
    cfg.pin_d1    = CAM_PIN_D1;
    cfg.pin_d0    = CAM_PIN_D0;
    cfg.pin_vsync = CAM_PIN_VSYNC;
    cfg.pin_href  = CAM_PIN_HREF;
    cfg.pin_pclk  = CAM_PIN_PCLK;

    // Anonymous unions: pin_sccb_sda / pin_siod  and  pin_sccb_scl / pin_sioc.
    // Writing via sda/scl variant; both names alias the same memory.
    cfg.__bindgen_anon_1.pin_sccb_sda = CAM_PIN_SIOD;
    cfg.__bindgen_anon_2.pin_sccb_scl = CAM_PIN_SIOC;

    cfg.xclk_freq_hz = CAM_XCLK_FREQ;
    // Use LEDC timer 1 / channel 1 — backlight occupies timer 0 / channel 0.
    cfg.ledc_timer   = cam::ledc_timer_t_LEDC_TIMER_1;
    cfg.ledc_channel = cam::ledc_channel_t_LEDC_CHANNEL_1;
    // I2C port 1 for SCCB (CONFIG_SCCB_HARDWARE_I2C_PORT=1); touch is on I2C0.
    cfg.sccb_i2c_port = 1;

    cfg.pixel_format = cam::pixformat_t_PIXFORMAT_GRAYSCALE;
    cfg.frame_size   = cam::framesize_t_FRAMESIZE_SVGA;
    cfg.jpeg_quality = 12;
    cfg.fb_count     = 2;
    cfg.grab_mode    = cam::camera_grab_mode_t_CAMERA_GRAB_LATEST;
    cfg.fb_location  = cam::camera_fb_location_t_CAMERA_FB_IN_PSRAM;

    let ret = cam::esp_camera_init(&cfg);
    if ret != esp_idf_sys::ESP_OK {
        return Err(format!("esp_camera_init failed: {ret:#010x}"));
    }

    // The sensor's default scan direction is mirrored relative to how the
    // camera faces the user on this board, so the preview (and the luma the
    // QR decoder sees) comes out flipped in X. Correct it at the sensor.
    // (hmirror, not vflip: this board's OV5640 is mounted such that hmirror
    // yields the correct, decodable handedness — confirmed by successful
    // decodes; a mirrored image would never decode with quirc.)
    let sensor = cam::esp_camera_sensor_get();
    if !sensor.is_null() {
        if let Some(set_hmirror) = (*sensor).set_hmirror {
            set_hmirror(sensor, 1);
        }
    }

    // Let the sensor's auto exposure / gain / white-balance settle before the
    // reader starts grabbing frames (mirrors Jade's post-init delay). The first
    // frames after init are otherwise mis-exposed and waste decode attempts.
    thread::sleep(Duration::from_millis(500));

    Ok(())
}

// ---------- reader thread ---------------------------------------------------

fn reader_loop(
    latest: Arc<Mutex<Option<Frame>>>,
    fatal: Arc<Mutex<Option<String>>>,
    stop: Arc<AtomicBool>,
) {
    // The camera driver occasionally returns NULL on a transient frame timeout
    // (the YUV422 DVP path is bandwidth-tight). Tolerate those and keep going —
    // only declare the camera dead after many consecutive failures. Previously a
    // single timeout tore down and reopened the camera, causing multi-second
    // dead periods mid-scan.
    let mut consecutive_nulls = 0u32;
    const MAX_CONSECUTIVE_NULLS: u32 = 30;

    loop {
        if stop.load(Ordering::Relaxed) {
            return;
        }

        // Blocking call — returns when the camera DMA has a frame ready.
        let fb = unsafe { esp_idf_sys::camera::esp_camera_fb_get() };

        if fb.is_null() {
            if stop.load(Ordering::Relaxed) {
                return; // NULL from esp_camera_deinit() on the Drop path.
            }
            consecutive_nulls += 1;
            if consecutive_nulls >= MAX_CONSECUTIVE_NULLS {
                if let Ok(mut g) = fatal.lock() {
                    if g.is_none() {
                        *g = Some("camera stopped delivering frames".to_string());
                    }
                }
                stop.store(true, Ordering::Relaxed);
                return;
            }
            thread::sleep(Duration::from_millis(50));
            continue;
        }
        consecutive_nulls = 0;

        let fb_ref = unsafe { &*fb };
        let npx = (fb_ref.width * fb_ref.height) as usize;

        // Skip torn / short frames. The DVP→PSRAM path can under-run and deliver
        // a frame shorter than expected (the driver logs "FB-SIZE: ... != ...").
        // Processing it as if full-size yields an undersized luma buffer →
        // out-of-bounds indexing in the decoder → heap corruption. In GRAYSCALE
        // the buffer is 1 byte/pixel, so a full frame is exactly `npx` bytes.
        if fb_ref.len < npx {
            unsafe { esp_idf_sys::camera::esp_camera_fb_return(fb) };
            thread::sleep(Duration::from_millis(10));
            continue;
        }

        // GRAYSCALE: the frame buffer *is* the luma plane. Copy it out so we can
        // hand the DMA buffer back to the camera before publishing.
        let luma = unsafe { core::slice::from_raw_parts(fb_ref.buf, npx) }.to_vec();

        // Return the DMA buffer before publishing — we're done reading it.
        unsafe { esp_idf_sys::camera::esp_camera_fb_return(fb) };

        let frame = Frame {
            width: fb_ref.width as u32,
            height: fb_ref.height as u32,
            rgb: Vec::new(),
            luma,
        };

        if let Ok(mut g) = latest.lock() {
            *g = Some(frame);
        }
    }
}

// ---------- decoder thread --------------------------------------------------

fn decoder_loop(
    latest: Arc<Mutex<Option<Frame>>>,
    pending_qr: Arc<Mutex<Option<Vec<u8>>>>,
    diag: Arc<Mutex<ScanDiagnostics>>,
    small_qr_mode: Arc<AtomicBool>,
    decode_enabled: Arc<AtomicBool>,
) {
    // Runs for the life of the process; gated by `decode_enabled` (set false
    // whenever no camera is open), so it never needs a stop signal.
    let mut ur_acc = faraday_core::qr::ur_decoder::UrAccumulator::new();
    loop {
        if !decode_enabled.load(Ordering::Relaxed) {
            ur_acc.reset();
            if let Ok(mut g) = diag.lock() {
                *g = ScanDiagnostics::default();
            }
            thread::sleep(Duration::from_millis(100));
            continue;
        }
        // Skip if a previous result is still waiting for the main thread.
        if pending_qr.lock().ok().map(|g| g.is_some()).unwrap_or(false) {
            thread::sleep(Duration::from_millis(50));
            continue;
        }
        // Clone only the luma plane, not the whole frame: the decode pipeline
        // never touches `rgb` (that's only for the preview blit on the main
        // thread), so copying the ~230 KB RGB buffer out of PSRAM every attempt
        // is pure waste. An empty `rgb` keeps the `Frame` shape the core helper
        // expects.
        let frame = match latest.lock() {
            Ok(g) => match g.as_ref() {
                Some(f) => Frame {
                    width: f.width,
                    height: f.height,
                    rgb: Vec::new(),
                    luma: f.luma.clone(),
                },
                None => {
                    drop(g);
                    thread::sleep(Duration::from_millis(50));
                    continue;
                }
            },
            Err(_) => {
                thread::sleep(Duration::from_millis(50));
                continue;
            }
        };
        let mode = if small_qr_mode.load(Ordering::Relaxed) {
            ScanMode::SmallQr
        } else {
            ScanMode::Full
        };
        let (decoded, saw_qr) =
            crate::qr_decode::try_decode_qr_ur_diag(&frame, &mut ur_acc, mode);
        if saw_qr {
            if let Ok(mut g) = diag.lock() {
                g.last_qr_at = Some(std::time::Instant::now());
                g.ur_progress = ur_acc.progress();
            }
        }
        if let Some(bytes) = decoded {
            if let Ok(mut g) = pending_qr.lock() {
                *g = Some(bytes);
            }
        }
        thread::sleep(Duration::from_millis(10));
    }
}

