//! OV2640 / OV5640 camera driver via ESP-IDF esp_camera component.
//!
//! Captures 320×240 QVGA in YUV422, converts to `Frame` (interleaved RGB +
//! luma plane), and publishes via `Arc<Mutex<Option<Frame>>>` — the same
//! pattern as `PiCamera` in the raspberry-pi crate.
//!
//! # GPIO pin assignments (Waveshare ESP32-S3-Touch-LCD-2)
//! These are the default FPC camera connector mapping. Verify against the
//! board schematic before use — Waveshare revisions sometimes differ.
//!
//!   SIOD (SDA)  GPIO 4   SCCB uses I2C1 (see CONFIG_SCCB_HARDWARE_I2C_PORT)
//!   SIOC (SCL)  GPIO 5   Touch uses I2C0 (GPIO48/47) — no conflict.
//!   XCLK        GPIO 15
//!   VSYNC       GPIO 6
//!   HREF        GPIO 7
//!   PCLK        GPIO 13
//!   D7 (Y9)     GPIO 16
//!   D6 (Y8)     GPIO 17
//!   D5 (Y7)     GPIO 18
//!   D4 (Y6)     GPIO 12
//!   D3 (Y5)     GPIO 10
//!   D2 (Y4)     GPIO 8
//!   D1 (Y3)     GPIO 9
//!   D0 (Y2)     GPIO 11
//!   PWDN / RESET not wired (-1)
//!
//! XCLK is generated by LEDC timer 1 + channel 1 (backlight uses timer 0 /
//! channel 0, so there is no conflict).

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::Duration;

use faraday_core::camera::{Frame, ScanDiagnostics, ScanMode};

// ---------- board pin constants -------------------------------------------
//
// From the Waveshare ESP32-S3-Touch-LCD-2 CircuitPython board definition
// (ports/espressif/boards/waveshare_esp32_s3_touch_lcd_2/pins.c) — the same
// authoritative source the display/touch pins were taken from.
//
// Camera SCCB is on its own I2C bus (SDA=21, SCL=16), separate from the touch
// sensor (I2C0, GPIO48/47). No RESET line is wired; PWDN is GPIO17 (active
// high: esp_camera_init drives it HIGH then LOW to power the sensor on).

const CAM_PIN_PWDN: i32  = 17;
const CAM_PIN_RESET: i32 = -1;
const CAM_PIN_XCLK: i32  = 8;
const CAM_PIN_SIOD: i32  = 21; // TWI_SDA
const CAM_PIN_SIOC: i32  = 16; // TWI_CLK
const CAM_PIN_D7: i32    = 2;
const CAM_PIN_D6: i32    = 7;
const CAM_PIN_D5: i32    = 10;
const CAM_PIN_D4: i32    = 14;
const CAM_PIN_D3: i32    = 11;
const CAM_PIN_D2: i32    = 15;
const CAM_PIN_D1: i32    = 13;
const CAM_PIN_D0: i32    = 12;
const CAM_PIN_VSYNC: i32 = 6;
const CAM_PIN_HREF: i32  = 4;
const CAM_PIN_PCLK: i32  = 9;

// 20 MHz XCLK — standard for OV2640 and OV5640.
const CAM_XCLK_FREQ: i32 = 20_000_000;

const CAPTURE_W: u32 = 320;
const CAPTURE_H: u32 = 240;

const FIRST_FRAME_TIMEOUT: Duration = Duration::from_secs(5);

// ---------- public struct ---------------------------------------------------

pub struct EspCamera {
    latest: Arc<Mutex<Option<Frame>>>,
    pending_qr: Arc<Mutex<Option<Vec<u8>>>>,
    diag: Arc<Mutex<ScanDiagnostics>>,
    small_qr_mode: Arc<AtomicBool>,
    fatal_err: Arc<Mutex<Option<String>>>,
    stop: Arc<AtomicBool>,
    decode_enabled: Arc<AtomicBool>,
    _reader: Option<JoinHandle<()>>,
    _decoder: Option<JoinHandle<()>>,
}

impl EspCamera {
    pub fn open() -> Result<Self, String> {
        unsafe { init_camera()? };
        log::info!("esp_camera: init OK ({}x{} YUV422)", CAPTURE_W, CAPTURE_H);

        let latest: Arc<Mutex<Option<Frame>>> = Arc::new(Mutex::new(None));
        let pending_qr: Arc<Mutex<Option<Vec<u8>>>> = Arc::new(Mutex::new(None));
        let diag: Arc<Mutex<ScanDiagnostics>> =
            Arc::new(Mutex::new(ScanDiagnostics::default()));
        let fatal_err: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));
        let stop = Arc::new(AtomicBool::new(false));
        let decode_enabled = Arc::new(AtomicBool::new(false));
        let small_qr_mode = Arc::new(AtomicBool::new(false));

        // Reader thread — grabs frames from the camera DMA, converts YUV422
        // to RGB+luma, publishes to `latest`. Stack: 16 KB for the conversion
        // buffers (320×240×5 bytes touched per frame).
        let latest_w = Arc::clone(&latest);
        let fatal_w = Arc::clone(&fatal_err);
        let stop_r = Arc::clone(&stop);
        let reader = thread::Builder::new()
            .stack_size(16 * 1024)
            .spawn(move || reader_loop(latest_w, fatal_w, stop_r))
            .map_err(|e| format!("spawn reader: {e}"))?;

        // Decoder thread — runs the quircs QR pipeline on the latest frame.
        // 32 KB stack: quircs does meaningful image processing (grid extraction
        // + Reed-Solomon decode) and needs the headroom.
        let latest_d = Arc::clone(&latest);
        let qr_d = Arc::clone(&pending_qr);
        let diag_d = Arc::clone(&diag);
        let mode_d = Arc::clone(&small_qr_mode);
        let stop_d = Arc::clone(&stop);
        let decode_d = Arc::clone(&decode_enabled);
        let decoder = thread::Builder::new()
            .stack_size(32 * 1024)
            .spawn(move || decoder_loop(latest_d, qr_d, diag_d, mode_d, stop_d, decode_d))
            .map_err(|e| format!("spawn decoder: {e}"))?;

        // Watchdog: report a fatal error if no frame arrives within 5 s.
        let latest_wd = Arc::clone(&latest);
        let fatal_wd = Arc::clone(&fatal_err);
        let stop_wd = Arc::clone(&stop);
        thread::Builder::new()
            .stack_size(4 * 1024)
            .spawn(move || {
                thread::sleep(FIRST_FRAME_TIMEOUT);
                if stop_wd.load(Ordering::Relaxed) {
                    return;
                }
                let got_frame =
                    latest_wd.lock().ok().map(|g| g.is_some()).unwrap_or(false);
                if got_frame {
                    return;
                }
                if let Ok(mut g) = fatal_wd.lock() {
                    if g.is_none() {
                        *g = Some("no frame in 5 s — check camera wiring".to_string());
                    }
                }
                stop_wd.store(true, Ordering::Relaxed);
            })
            .ok(); // watchdog failure is non-fatal

        Ok(EspCamera {
            latest,
            pending_qr,
            diag,
            small_qr_mode,
            fatal_err,
            stop,
            decode_enabled,
            _reader: Some(reader),
            _decoder: Some(decoder),
        })
    }

    pub fn latest(&self) -> Option<Frame> {
        self.latest.lock().ok().and_then(|g| g.clone())
    }

    pub fn take_qr(&self) -> Option<Vec<u8>> {
        self.pending_qr.lock().ok().and_then(|mut g| g.take())
    }

    pub fn set_decode_enabled(&self, on: bool) {
        self.decode_enabled.store(on, Ordering::Relaxed);
    }

    pub fn set_small_qr_mode(&self, on: bool) {
        self.small_qr_mode.store(on, Ordering::Relaxed);
    }

    pub fn take_fatal_err(&self) -> Option<String> {
        self.fatal_err.lock().ok().and_then(|mut g| g.take())
    }

    pub fn diagnostics(&self) -> ScanDiagnostics {
        self.diag.lock().ok().map(|g| *g).unwrap_or_default()
    }
}

impl Drop for EspCamera {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::SeqCst);
        // Deinit causes esp_camera_fb_get() to return NULL, which unblocks the
        // reader thread so it sees the stop flag and exits cleanly.
        unsafe {
            esp_idf_sys::camera::esp_camera_deinit();
        }
        if let Some(h) = self._reader.take() {
            let _ = h.join();
        }
        if let Some(h) = self._decoder.take() {
            let _ = h.join();
        }
    }
}

// ---------- camera init (unsafe FFI) ----------------------------------------

unsafe fn init_camera() -> Result<(), String> {
    use esp_idf_sys::camera as cam;

    // Zero-initialise first so any fields not explicitly set below are at a
    // safe default (0 / false / null).
    let mut cfg: cam::camera_config_t = core::mem::zeroed();

    cfg.pin_pwdn  = CAM_PIN_PWDN;
    cfg.pin_reset = CAM_PIN_RESET;
    cfg.pin_xclk  = CAM_PIN_XCLK;
    cfg.pin_d7    = CAM_PIN_D7;
    cfg.pin_d6    = CAM_PIN_D6;
    cfg.pin_d5    = CAM_PIN_D5;
    cfg.pin_d4    = CAM_PIN_D4;
    cfg.pin_d3    = CAM_PIN_D3;
    cfg.pin_d2    = CAM_PIN_D2;
    cfg.pin_d1    = CAM_PIN_D1;
    cfg.pin_d0    = CAM_PIN_D0;
    cfg.pin_vsync = CAM_PIN_VSYNC;
    cfg.pin_href  = CAM_PIN_HREF;
    cfg.pin_pclk  = CAM_PIN_PCLK;

    // Anonymous unions: pin_sccb_sda / pin_siod  and  pin_sccb_scl / pin_sioc.
    // Writing via sda/scl variant; both names alias the same memory.
    cfg.__bindgen_anon_1.pin_sccb_sda = CAM_PIN_SIOD;
    cfg.__bindgen_anon_2.pin_sccb_scl = CAM_PIN_SIOC;

    cfg.xclk_freq_hz = CAM_XCLK_FREQ;
    // Use LEDC timer 1 / channel 1 — backlight occupies timer 0 / channel 0.
    cfg.ledc_timer   = cam::ledc_timer_t_LEDC_TIMER_1;
    cfg.ledc_channel = cam::ledc_channel_t_LEDC_CHANNEL_1;
    // I2C port 1 for SCCB (CONFIG_SCCB_HARDWARE_I2C_PORT=1); touch is on I2C0.
    cfg.sccb_i2c_port = 1;

    cfg.pixel_format = cam::pixformat_t_PIXFORMAT_YUV422;
    cfg.frame_size   = cam::framesize_t_FRAMESIZE_QVGA;
    cfg.jpeg_quality = 12;
    cfg.fb_count     = 2;
    cfg.grab_mode    = cam::camera_grab_mode_t_CAMERA_GRAB_LATEST;
    cfg.fb_location  = cam::camera_fb_location_t_CAMERA_FB_IN_PSRAM;

    let ret = cam::esp_camera_init(&cfg);
    if ret != esp_idf_sys::ESP_OK {
        return Err(format!("esp_camera_init failed: {ret:#010x}"));
    }

    // The sensor's default scan direction is mirrored relative to how the
    // camera faces the user on this board, so the preview (and the luma the
    // QR decoder sees) comes out flipped in X. Correct it at the sensor.
    let sensor = cam::esp_camera_sensor_get();
    if !sensor.is_null() {
        if let Some(set_hmirror) = (*sensor).set_hmirror {
            set_hmirror(sensor, 1);
        }
    }

    Ok(())
}

// ---------- reader thread ---------------------------------------------------

fn reader_loop(
    latest: Arc<Mutex<Option<Frame>>>,
    fatal: Arc<Mutex<Option<String>>>,
    stop: Arc<AtomicBool>,
) {
    loop {
        if stop.load(Ordering::Relaxed) {
            return;
        }

        // Blocking call — returns when the camera DMA has a frame ready.
        let fb = unsafe { esp_idf_sys::camera::esp_camera_fb_get() };

        if fb.is_null() {
            // NULL after deinit (Drop path) or hardware error.
            if !stop.load(Ordering::Relaxed) {
                if let Ok(mut g) = fatal.lock() {
                    if g.is_none() {
                        *g = Some("esp_camera_fb_get returned NULL".to_string());
                    }
                }
                stop.store(true, Ordering::Relaxed);
            }
            return;
        }

        let fb_ref = unsafe { &*fb };
        let data = unsafe {
            core::slice::from_raw_parts(fb_ref.buf, fb_ref.len)
        };

        let (rgb, luma) =
            yuv422_to_rgb_luma(data, fb_ref.width as u32, fb_ref.height as u32);

        // Return the DMA buffer before publishing — conversion is done.
        unsafe { esp_idf_sys::camera::esp_camera_fb_return(fb) };

        let frame = Frame {
            width: fb_ref.width as u32,
            height: fb_ref.height as u32,
            rgb,
            luma,
        };

        if let Ok(mut g) = latest.lock() {
            *g = Some(frame);
        }
    }
}

// ---------- decoder thread --------------------------------------------------

fn decoder_loop(
    latest: Arc<Mutex<Option<Frame>>>,
    pending_qr: Arc<Mutex<Option<Vec<u8>>>>,
    diag: Arc<Mutex<ScanDiagnostics>>,
    small_qr_mode: Arc<AtomicBool>,
    stop: Arc<AtomicBool>,
    decode_enabled: Arc<AtomicBool>,
) {
    let mut ur_acc = faraday_core::qr::ur_decoder::UrAccumulator::new();
    loop {
        if stop.load(Ordering::Relaxed) {
            return;
        }
        if !decode_enabled.load(Ordering::Relaxed) {
            ur_acc.reset();
            if let Ok(mut g) = diag.lock() {
                *g = ScanDiagnostics::default();
            }
            thread::sleep(Duration::from_millis(100));
            continue;
        }
        // Skip if a previous result is still waiting for the main thread.
        if pending_qr.lock().ok().map(|g| g.is_some()).unwrap_or(false) {
            thread::sleep(Duration::from_millis(50));
            continue;
        }
        let frame = match latest.lock().ok().and_then(|g| g.clone()) {
            Some(f) => f,
            None => {
                thread::sleep(Duration::from_millis(50));
                continue;
            }
        };
        let mode = if small_qr_mode.load(Ordering::Relaxed) {
            ScanMode::SmallQr
        } else {
            ScanMode::Full
        };
        let (decoded, saw_qr) =
            crate::qr_decode::try_decode_qr_ur_diag(&frame, &mut ur_acc, mode);
        if saw_qr {
            if let Ok(mut g) = diag.lock() {
                g.last_qr_at = Some(std::time::Instant::now());
                g.ur_progress = ur_acc.progress();
            }
        }
        if let Some(bytes) = decoded {
            if let Ok(mut g) = pending_qr.lock() {
                *g = Some(bytes);
            }
        }
        thread::sleep(Duration::from_millis(10));
    }
}

// ---------- YUV422 (YUYV) → interleaved RGB + luma -------------------------
//
// YUYV packing: Y0 U0 Y1 V0 per 4-byte block covering pixels 0 and 1.
// Luma: bytes at even positions (0, 2, 4, …).
// Chroma: Cb = U byte (offset 1), Cr = V byte (offset 3), shared by 2 pixels.

fn yuv422_to_rgb_luma(data: &[u8], w: u32, h: u32) -> (Vec<u8>, Vec<u8>) {
    let npx = (w * h) as usize;
    let mut rgb = vec![0u8; npx * 3];
    let mut luma = vec![0u8; npx];

    let mut i = 0usize; // byte index into data (advances by 4)
    let mut px = 0usize; // pixel index (advances by 2)

    while i + 3 < data.len() && px + 1 < npx {
        let y0 = data[i] as i32;
        let u  = data[i + 1] as i32;
        let y1 = data[i + 2] as i32;
        let v  = data[i + 3] as i32;

        luma[px]     = y0 as u8;
        luma[px + 1] = y1 as u8;

        let (r0, g0, b0) = yuv_to_rgb(y0, u, v);
        let (r1, g1, b1) = yuv_to_rgb(y1, u, v);

        rgb[px * 3]             = r0;
        rgb[px * 3 + 1]         = g0;
        rgb[px * 3 + 2]         = b0;
        rgb[(px + 1) * 3]       = r1;
        rgb[(px + 1) * 3 + 1]   = g1;
        rgb[(px + 1) * 3 + 2]   = b1;

        i  += 4;
        px += 2;
    }

    (rgb, luma)
}

#[inline(always)]
fn yuv_to_rgb(y: i32, u: i32, v: i32) -> (u8, u8, u8) {
    let c = y - 16;
    let d = u - 128;
    let e = v - 128;
    let r = ((298 * c + 409 * e + 128) >> 8).clamp(0, 255) as u8;
    let g = ((298 * c - 100 * d - 208 * e + 128) >> 8).clamp(0, 255) as u8;
    let b = ((298 * c + 516 * d + 128) >> 8).clamp(0, 255) as u8;
    (r, g, b)
}
